name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    tags:
      - 'v*'  # trigger on tags like v0.1.12

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract tag name
      id: get_tag
      run: echo "TAG=${GITHUB_REF##*/}" >> $GITHUB_ENV

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          famalama/usms-scrape:latest
          famalama/usms-scrape:${{ env.TAG }}


