name: Build and Push Docker Image

on:
  push:
    branches:
      - main
      - dev
    tags:
      - 'v*'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Determine Docker tags
        id: set_tags
        run: |
          TAGS=""
          if [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
            TAGS="famalama/usms-scrape:stable"
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            TAGS="famalama/usms-scrape:dev"
          elif [[ "${GITHUB_REF}" =~ refs/tags/v.* ]]; then
            VERSION_TAG=${GITHUB_REF##*/}
            TAGS="famalama/usms-scrape:${VERSION_TAG} famalama/usms-scrape:stable"
          fi
          echo "tags=${TAGS}" >> $GITHUB_OUTPUT

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ steps.set_tags.outputs.tags }}
